### ISSUE TITLE
Handle right panel

### ISSUE THREAD

**Issue by Q-Zhao** [Q-Zhao/dataviz-project-QZhao#3]
Once a country is selected from left earth panel, a specific country is chosen. This task is to create 2 figures, and a slider for the right panel. 
 - The first should be a scatter chart reflexing the relationship between number of Internet users and GDP.
 - The second should be a bar chart, where one bar is the Internet user percentage, and the other is the mobile subscriber percentage per 100 people in that country in a specific year.
 - The slider should be present to let user to select a specific year. By doing so, the bar chart should be updated.

**Comment by FanYang715** [comment]
This idea seems pretty cool!

**Comment by curran** [comment]
Cool ideas! This could be split up into smaller issues:

 * Add country selection ability to the map
 * Define what exactly happens when a country is selected
   * Linked highlighting in the other views?
 * Create scatter plot
 * Create bar chart
 * Create time slider
 * Update the bar chart when the time slider updates

Not sure if you are planning for these, but the following might also make sense:

 * Update the map when the time slider updates
 * Update the scatter plot when the time slider updates

So each of the above bullets could be their own separate GitHub issue, which you can work on one by one.

Great ideas!
